version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - chromadb
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file: .env

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
