[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "nodejs", "pnpm"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd frontend && pnpm install"
]

[start]
cmd = "uvicorn src.api.main:app --host 0.0.0.0 --port $PORT" 