[build]
builder = "nixpacks"
buildCommand = "cd /app && pip install -r requirements.txt"

[deploy]
startCommand = "cd /app && uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 3 