[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y python3-pip && pip3 install -r requirements.txt && cd frontend && pnpm install"

[deploy]
startCommand = "uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 3 