# AI Configuration

# Model settings
models:
  primary:
    name: "gpt-4"
    temperature: 0.7
    max_tokens: 2000
  secondary:
    name: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 2000

# Memory settings
memory:
  short_term:
    expiration: 3600  # 1 hour in seconds
  long_term:
    collection_name: "geometra_memory"
    embedding_model: "text-embedding-ada-002"

# Prompt settings
prompts:
  templates_dir: "templates/prompts"
  default_template: "chat"

# Fallback settings
fallback:
  max_retries: 3
  retry_delay: 1  # seconds
  strategies:
    rate_limit:
      action: "wait_and_retry"
      wait_time: 60
    timeout:
      action: "immediate_fallback"
    unknown_error:
      action: "retry_with_backoff"
      max_wait: 30

# Evaluation settings
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
  thresholds:
    accuracy: 0.8
    f1_score: 0.7

# Training settings
training:
  batch_size: 32
  epochs: 3
  learning_rate: 1e-5
  validation_split: 0.2 